[[redirects]]
    from = "http://fractaldimensions.io/*"
    to = "https://fd.digital"
    status = 301
    force = true # COMMENT: ensure that we always redirect
    headers = { X-From = "Netlify" }

[[redirects]]
    from = "https://fractaldimensions.io/*"
    to = "https://fd.digital"
    status = 301
    force = true # COMMENT: ensure that we always redirect
    headers = { X-From = "Netlify" }

[[redirects]]
    from = "https://www.fractaldimensions.io/*"
    to = "https://fd.digital"
    status = 301
    force = true # COMMENT: ensure that we always redirect
    headers = { X-From = "Netlify" }

[[redirects]]
    from = "http://www.fractaldimensions.io/*"
    to = "https://fd.digital"
    status = 301
    force = true # COMMENT: ensure that we always redirect
    headers = { X-From = "Netlify" }

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net/ https://www.googletagmanager.com https://www.google-analytics.com/; img-src 'self' www.google-analytics.com www.googletagmanager.com; style-src 'self' https://fonts.googleapis.com/ cdn.jsdelivr.net 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU='; connect-src 'self' https://www.google-analytics.com"
